#!/usr/bin/env bash
# This Script Will Display domain name's subdomains

if [ $# -eq 1 ]; 
then
    declare subdomains=('www' 'lb-01' 'web-01' 'web-02')
    for subdomain in ${subdomains[@]};
    do
         host_ip=$(dig "$subdomain.$1" | awk '/ANSWER SECTION:/ {getline; print $5}')
         record_type=$(dig "$subdomain.$1" | awk '/ANSWER SECTION:/ {getline; print $4}')
         echo "The subdomain $subdomain is a $record_type record and points to $host_ip"
    done
elif [ $# -eq 2 ];
then
    host_ip=$(dig "$2.$1" | awk '/ANSWER SECTION:/ {getline; print $5}')
    record_type=$(dig "$2.$1" | awk '/ANSWER SECTION:/ {getline; print $4}')
    echo "The subdomain $2 is a $record_type record and points to $host_ip"
fi