#!/usr/bin/env bash
# SSH client configuration

Host *
	PasswordAuthentication no
	IdentityFile ~/.ssh/school
	SendEnv LANG LC_*
	HashKnowHosts yes
	GSSAPIAuthentication yes
	GSSAPIDelegateCredentials no
